export const ERROR_CODES = {
  // IM adapters
  IM_UNRESOLVABLE_TARGET: "IM_UNRESOLVABLE_TARGET",
  IM_SEND_FAILED: "IM_SEND_FAILED",
  IM_TOKEN_INVALID: "IM_TOKEN_INVALID",
  IM_TOKEN_MISSING: "IM_TOKEN_MISSING",
  IM_CHANNEL_NOT_CONFIGURED: "IM_CHANNEL_NOT_CONFIGURED",
  IM_MESSAGE_TOO_LONG: "IM_MESSAGE_TOO_LONG",
  IM_RATE_LIMITED: "IM_RATE_LIMITED",
  IM_TIMEOUT: "IM_TIMEOUT",

  // Judge
  JUDGE_TIMEOUT: "JUDGE_TIMEOUT",
  JUDGE_PARSE_FAILED: "JUDGE_PARSE_FAILED",
  JUDGE_MODEL_NOT_CONFIGURED: "JUDGE_MODEL_NOT_CONFIGURED",
  JUDGE_COOLDOWN: "JUDGE_COOLDOWN",
  JUDGE_ENDPOINT_UNREACHABLE: "JUDGE_ENDPOINT_UNREACHABLE",

  // OpenClaw
  OPENCLAW_NOT_FOUND: "OPENCLAW_NOT_FOUND",
  OPENCLAW_CONFIG_UNREADABLE: "OPENCLAW_CONFIG_UNREADABLE",
  OPENCLAW_CONFIG_UNWRITABLE: "OPENCLAW_CONFIG_UNWRITABLE",

  // Dispatch
  DISPATCH_ADMISSION_DENIED: "DISPATCH_ADMISSION_DENIED",
  DISPATCH_NO_ELIGIBLE_MODEL: "DISPATCH_NO_ELIGIBLE_MODEL",
  DISPATCH_TIMEOUT: "DISPATCH_TIMEOUT",

  // Router
  ROUTER_SNAPSHOT_MISSING: "ROUTER_SNAPSHOT_MISSING",
  ROUTER_SNAPSHOT_STALE: "ROUTER_SNAPSHOT_STALE",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
