import fsSync from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { ContextCoverageSnapshot } from "@octoclaw/contracts/work-contract";
import { resetAllState as resetAckDedupeState } from "../ack/ack-dedupe.js";
import { resetExecTransitionState } from "../ack/execution-transition-notifier.js";
import { buildExecutionCoverageLayer } from "../resolve/execution-coverage-precheck.js";
import { buildMemoryCoverageLayer } from "../resolve/memory-coverage-precheck.js";
import { envOverrides } from "../resolve/env.js";
import { buildWorkContractFromPolicy, buildWorkDecisionSeal } from "../work-contract/builders.js";
import { loadWorkContract, saveWorkContract, updateWorkContract } from "../work-contract/store.js";
import { confirmNativeSpawn } from "./native-spawn-confirm.js";
import { evaluateNativeSessionsSendGate, evaluateNativeSpawnGate } from "./native-spawn-gate.js";
import { nativeSpawnIntentStore } from "./native-spawn-intent-store.js";
import type { SessionsSpawnArgs } from "./native-spawn-intent.js";

const mockSendIMMessage = vi.hoisted(() => vi.fn());

vi.mock("../im/send.js", () => ({
  sendIMMessage: mockSendIMMessage,
}));

const fs = fsSync as unknown as {
  mkdtempSync(pathname: string): string;
  rmSync(pathname: string, options?: { recursive?: boolean; force?: boolean }): void;
};
const osModule = os as unknown as { tmpdir(): string };

let tempWorkspace = "";

const args: SessionsSpawnArgs = {
  task: "Research the native planner confirm handshake.",
  label: "planner confirm",
  runtime: "subagent",
  model: "zhipu/GLM-5.1",
  mode: "run",
  cleanup: "keep",
  sandbox: "inherit",
  context: "isolated",
  lightContext: true,
};

function coverageSnapshot(): ContextCoverageSnapshot {
  const execution = buildExecutionCoverageLayer(["missing"]);
  const memory = buildMemoryCoverageLayer();
  return {
    precheckOrder: [
      "conversation_grounding",
      "continuation_route_reuse",
      "execution_coverage",
      "memory_coverage",
      "build_judge_context_packet",
      "local_judge",
      "validator_or_remote",
      "route_seal_commit",
    ],
    execution,
    memory,
    conflict: false,
    authority: "none" as const,
  };
}

function seedContract(sessionKey = "session-native-spawn-confirm") {
  const contract = buildWorkContractFromPolicy(
    sessionKey,
    "Research the planner confirm handshake and summarize it.",
    "fresh_live_lookup",
    coverageSnapshot(),
    buildWorkDecisionSeal("local_judge", "delegate", ["native_spawn_test"]),
    { status: "sealed" },
  );
  saveWorkContract(contract);
  return contract;
}

beforeEach(() => {
  tempWorkspace = fs.mkdtempSync(path.join(osModule.tmpdir(), "octoclaw-native-spawn-gate-confirm-"));
  envOverrides.workspaceRoot = tempWorkspace;
  nativeSpawnIntentStore.clearForTests();
  resetAckDedupeState();
  resetExecTransitionState();
  vi.restoreAllMocks();
  mockSendIMMessage.mockReset();
  mockSendIMMessage.mockResolvedValue({ sent: true, threadTs: "1700000000.000100" });
});

afterEach(() => {
  vi.restoreAllMocks();
  resetAckDedupeState();
  resetExecTransitionState();
  nativeSpawnIntentStore.clearForTests();
  envOverrides.workspaceRoot = "";
  if (tempWorkspace) fs.rmSync(tempWorkspace, { recursive: true, force: true });
  tempWorkspace = "";
});

describe("evaluateNativeSpawnGate", () => {
  it("allows matching sessions_spawn args and moves intent to spawn_call_started", () => {
    const intent = nativeSpawnIntentStore.create({
      workContractId: "wc-gate",
      sessionKey: "session-gate",
      sessionsSpawnArgs: args,
      ttlMs: 60_000,
    });

    const allowed = evaluateNativeSpawnGate({ sessionKeys: ["session-gate"], args });

    expect(allowed.allowed).toBe(true);
    expect(allowed.allowed ? allowed.intent.spawnIntentId : "").toBe(intent.spawnIntentId);
    expect(nativeSpawnIntentStore.get(intent.spawnIntentId)?.status).toBe("spawn_call_started");
  });

  it("allows exact planner task args when only the display label is shortened", () => {
    const plannerArgs: SessionsSpawnArgs = {
      ...args,
      task: [
        "[OctoClaw delegated work]",
        "workContractId: wc-label-only",
        "delegateTaskId: delegate-task:wc-label-only",
        "attemptId: delegate-task:wc-label-only:attempt:1",
        "Expected deliverable:",
        "只读检查 OpenClaw Gateway 和 OctoClaw 的当前就绪状态。具体步骤：",
        "## Runtime Context Packet",
        "This packet is generated by OctoClaw runtime; do not infer hidden parent transcript.",
        "```json",
        "{",
        '  "workContractId": "wc-label-only"',
        "}",
        "```",
        "Task:",
        "只读检查 OpenClaw Gateway 和 OctoClaw 的当前就绪状态。具体步骤：",
      ].join("\n"),
      label: "只读检查 OpenClaw Gateway 和 OctoClaw 的当前就绪状态。具体步骤：\n1. 运行 `openclaw status` 获取 Gateway 状态… [wc-label-only]",
    };

    const intent = nativeSpawnIntentStore.create({
      workContractId: "wc-label-only",
      sessionKey: "session-label-only",
      sessionsSpawnArgs: plannerArgs,
      ttlMs: 60_000,
    });

    const allowed = evaluateNativeSpawnGate({
      sessionKeys: ["session-label-only"],
      args: {
        ...plannerArgs,
        label: "只读检查 OpenClaw Gateway 和 OctoClaw 的当前就绪状态 [wc-label-only]",
      },
    });

    expect(allowed.allowed).toBe(true);
    expect(allowed.allowed ? allowed.intent.spawnIntentId : "").toBe(intent.spawnIntentId);
  });

  it("normalizes OpenClaw default/enriched args without weakening meaningful fields", () => {
    const intent = nativeSpawnIntentStore.create({
      workContractId: "wc-normalized",
      sessionKey: "session-normalized",
      sessionsSpawnArgs: args,
      ttlMs: 60_000,
    });

    const allowed = evaluateNativeSpawnGate({
      sessionKeys: ["session-normalized"],
      args: {
        ...args,
        agentId: "",
        thinking: "",
        timeoutSeconds: 0,
        thread: false,
        attachments: [],
        attachAs: { mountPath: "" },
      },
    });

    expect(allowed.allowed).toBe(true);
    expect(allowed.allowed ? allowed.intent.spawnIntentId : "").toBe(intent.spawnIntentId);
  });

  it("allows copied planner args when only JSON escape depth and display label whitespace drift", () => {
    const task = [
      "[OctoClaw delegated work]",
      "workContractId: wc-6e761cded9cbf8ff",
      "## Runtime Context Packet",
      "```json",
      "{",
      '  "currentUserAsk": "查询当前系统运行状态并汇总：\\n1. 运行 `openclaw status`\\n2. 运行 `uptime`"',
      "}",
      "```",
      "Task:",
      "查询当前系统运行状态并汇总：",
      "1. 运行 `openclaw status`",
    ].join("\n");
    const label = "查询当前系统运行状态并汇总：\n1. 运行 `openclaw status`\n2.… [wc-6e761cded9cbf8ff]";
    const storedArgs: SessionsSpawnArgs = { ...args, task, label };
    const copiedArgs: SessionsSpawnArgs = {
      ...storedArgs,
      task: task.replaceAll("\\n", "\\\\n"),
      label: "查询当前系统运行状态并汇总：1. 运行 `openclaw status`2.… [wc-6e761cded9cbf8ff]",
    };

    const intent = nativeSpawnIntentStore.create({
      workContractId: "wc-copied-planner",
      sessionKey: "session-copied-planner",
      sessionsSpawnArgs: storedArgs,
      ttlMs: 60_000,
    });

    const allowed = evaluateNativeSpawnGate({
      sessionKeys: ["session-copied-planner"],
      args: copiedArgs,
    });

    expect(allowed.allowed).toBe(true);
    expect(allowed.allowed ? allowed.intent.spawnIntentId : "").toBe(intent.spawnIntentId);
  });

  it("allows copied planner args when only a truncated expected-deliverable prefix is completed", () => {
    const expectedTask = [
      "[OctoClaw delegated work]",
      "workContractId: wc-recoverable-prefix",
      "delegateTaskId: delegate-task:wc-recoverable-prefix",
      "attemptId: delegate-task:wc-recoverable-prefix:attempt:1",
      "Expected deliverable:",
      "确认 OpenClaw Gateway 和 OctoClaw readiness 状态，分别概括 Gateway 状态、Oc",
      "## Runtime Context Packet",
      "This packet is generated by OctoClaw runtime; do not infer hidden parent transcript.",
      "```json",
      "{",
      '  "schemaVersion": "octoclaw.planner_native_context.v1",',
      '  "workContractId": "wc-recoverable-prefix",',
      '  "delegateTaskId": "delegate-task:wc-recoverable-prefix",',
      '  "attemptId": "delegate-task:wc-recoverable-prefix:attempt:1"',
      "}",
      "```",
      "Operational rules:",
      "- Native announce handles final delivery; do not create side-channel result files.",
      "Rules:",
      "- Work only on the task below; do not expose hidden reasoning or raw transcript.",
      "Task:",
      "确认 OpenClaw Gateway 和 OctoClaw readiness 状态，分别概括 Gateway 状态、OctoClaw 状态、整体健康评估。",
    ].join("\n");
    const copiedTask = expectedTask.replace(
      "分别概括 Gateway 状态、Oc\n## Runtime Context Packet",
      "分别概括 Gateway 状态、OctoClaw 状态、整体健康评估。\n## Runtime Context Packet",
    );
    const storedArgs: SessionsSpawnArgs = {
      ...args,
      task: expectedTask,
      label: "确认 Gateway 和 OctoClaw readiness… [wc-recoverable-prefix]",
    };

    const intent = nativeSpawnIntentStore.create({
      workContractId: "wc-recoverable-prefix",
      sessionKey: "session-recoverable-prefix",
      sessionsSpawnArgs: storedArgs,
      ttlMs: 60_000,
    });

    const allowed = evaluateNativeSpawnGate({
      sessionKeys: ["session-recoverable-prefix"],
      args: { ...storedArgs, task: copiedTask },
    });

    expect(allowed.allowed).toBe(true);
    expect(allowed.allowed ? allowed.intent.spawnIntentId : "").toBe(intent.spawnIntentId);
    expect(nativeSpawnIntentStore.get(intent.spawnIntentId)?.status).toBe("spawn_call_started");
  });

  it("allows copied planner args when completed prefix also shortens the display label", () => {
    const expectedTask = [
      "[OctoClaw delegated work]",
      "workContractId: wc-recoverable-label",
      "delegateTaskId: delegate-task:wc-recoverable-label",
      "attemptId: delegate-task:wc-recoverable-label:attempt:1",
      "Expected deliverable:",
      "最后用中文输出 3",
      "## Runtime Context Packet",
      "This packet is generated by OctoClaw runtime; do not infer hidden parent transcript.",
      "```json",
      "{",
      '  "workContractId": "wc-recoverable-label"',
      "}",
      "```",
      "Task:",
      "最后用中文输出 3 条摘要（每条一行）。",
    ].join("\n");
    const copiedTask = expectedTask.replace(
      "最后用中文输出 3\n## Runtime Context Packet",
      "最后用中文输出 3 条摘要（每条一行）。\n## Runtime Context Packet",
    );
    const storedArgs: SessionsSpawnArgs = {
      ...args,
      task: expectedTask,
      label: "最后用中文输出 3 条摘要（每条一行）… [wc-recoverable-label]",
    };

    const intent = nativeSpawnIntentStore.create({
      workContractId: "wc-recoverable-label",
      sessionKey: "session-recoverable-label",
      sessionsSpawnArgs: storedArgs,
      ttlMs: 60_000,
    });

    const allowed = evaluateNativeSpawnGate({
      sessionKeys: ["session-recoverable-label"],
      args: { ...storedArgs, task: copiedTask, label: "只读检查任务 [wc-recoverable-label]" },
    });

    expect(allowed.allowed).toBe(true);
    expect(allowed.allowed ? allowed.intent.spawnIntentId : "").toBe(intent.spawnIntentId);
  });

  it("allows copied planner args when a blank line is inserted before the runtime context packet", () => {
    const expectedTask = [
      "[OctoClaw delegated work]",
      "workContractId: wc-recoverable-blank",
      "delegateTaskId: delegate-task:wc-recoverable-blank",
      "attemptId: delegate-task:wc-recoverable-blank:attempt:1",
      "Expected deliverable:",
      "最后用中文输出 3",
      "## Runtime Context Packet",
      "This packet is generated by OctoClaw runtime; do not infer hidden parent transcript.",
      "```json",
      "{",
      '  "workContractId": "wc-recoverable-blank"',
      "}",
      "```",
      "Task:",
      "最后用中文输出 3 条摘要（每条一行）。",
    ].join("\n");
    const copiedTask = expectedTask.replace(
      "最后用中文输出 3\n## Runtime Context Packet",
      "最后用中文输出 3\n\n## Runtime Context Packet",
    );
    const storedArgs: SessionsSpawnArgs = {
      ...args,
      task: expectedTask,
      label: "最后用中文输出 3… [wc-recoverable-blank]",
    };

    const intent = nativeSpawnIntentStore.create({
      workContractId: "wc-recoverable-blank",
      sessionKey: "session-recoverable-blank",
      sessionsSpawnArgs: storedArgs,
      ttlMs: 60_000,
    });

    const allowed = evaluateNativeSpawnGate({
      sessionKeys: ["session-recoverable-blank"],
      args: { ...storedArgs, task: copiedTask },
    });

    expect(allowed.allowed).toBe(true);
    expect(allowed.allowed ? allowed.intent.spawnIntentId : "").toBe(intent.spawnIntentId);
  });

  it("blocks copied planner args when the runtime context suffix is missing", () => {
    const expectedTask = [
      "[OctoClaw delegated work]",
      "workContractId: wc-missing-suffix",
      "delegateTaskId: delegate-task:wc-missing-suffix",
      "attemptId: delegate-task:wc-missing-suffix:attempt:1",
      "Expected deliverable:",
      "确认 OpenClaw Gateway 和 OctoClaw readiness 状态，分别概括 Gateway 状态、Oc",
      "## Runtime Context Packet",
      "```json",
      "{",
      '  "workContractId": "wc-missing-suffix"',
      "}",
      "```",
      "Task:",
      "确认 OpenClaw Gateway 和 OctoClaw readiness 状态。",
    ].join("\n");
    const storedArgs: SessionsSpawnArgs = {
      ...args,
      task: expectedTask,
      label: "确认 Gateway 和 OctoClaw readiness… [wc-missing-suffix]",
    };

    nativeSpawnIntentStore.create({
      workContractId: "wc-missing-suffix",
      sessionKey: "session-missing-suffix",
      sessionsSpawnArgs: storedArgs,
      ttlMs: 60_000,
    });

    const blocked = evaluateNativeSpawnGate({
      sessionKeys: ["session-missing-suffix"],
      args: {
        ...storedArgs,
        task: "[OctoClaw delegated work]\nworkContractId: wc-missing-suffix\ndelegateTaskId: delegate-task:wc-missing-suffix",
      },
    });

    expect(blocked.allowed).toBe(false);
    expect(blocked.reason).toBe("args_hash_mismatch");
  });

  it("blocks planner sessions_spawn args when the isolated context flag is missing", () => {
    nativeSpawnIntentStore.create({
      workContractId: "wc-context-isolated",
      sessionKey: "session-context-isolated",
      sessionsSpawnArgs: args,
      ttlMs: 60_000,
    });

    const { context: _context, ...missingContext } = args;
    const blocked = evaluateNativeSpawnGate({
      sessionKeys: ["session-context-isolated"],
      args: missingContext,
    });

    expect(blocked.allowed).toBe(false);
    expect(blocked.reason).toBe("args_hash_mismatch");
  });

  it("blocks expired pending intent and marks it expired", () => {
    const createdAt = new Date("2026-05-02T12:00:00.000Z");
    const intent = nativeSpawnIntentStore.create({
      workContractId: "wc-expired",
      sessionKey: "session-expired",
      sessionsSpawnArgs: args,
      ttlMs: 50,
      now: createdAt,
    });

    const blocked = evaluateNativeSpawnGate({
      sessionKeys: ["session-expired"],
      args,
      now: new Date(createdAt.getTime() + 51),
    });

    expect(blocked.allowed).toBe(false);
    expect(blocked.reason).toBe("missing_pending_intent");
    expect(nativeSpawnIntentStore.get(intent.spawnIntentId)?.status).toBe("expired");
  });

  it("blocks hash mismatch and execution follow-up spawns", () => {
    nativeSpawnIntentStore.create({
      workContractId: "wc-mismatch",
      sessionKey: "session-mismatch",
      sessionsSpawnArgs: args,
      ttlMs: 60_000,
    });

    const mismatch = evaluateNativeSpawnGate({ sessionKeys: ["session-mismatch"], args: { ...args, task: "changed" } });
    expect(mismatch.allowed).toBe(false);
    expect(mismatch.reason).toBe("args_hash_mismatch");

    const followup = evaluateNativeSpawnGate({
      sessionKeys: ["session-mismatch"],
      args,
      decision: { request: { metadata: { conversation_control: { intent_class: "execution_followup" } } } },
    });
    expect(followup.allowed).toBe(false);
    expect(followup.reason).toBe("execution_followup_spawn_blocked");
  });

  it("does not authorize send_to_speculative intents through sessions_spawn", () => {
    const sendArgs = {
      message: "Run delegated task through standby session.",
      label: "octoclaw-speculative-gate",
      timeoutSeconds: 0,
    } as unknown as SessionsSpawnArgs;
    nativeSpawnIntentStore.create({
      workContractId: "wc-speculative-gate",
      sessionKey: "session-speculative-gate",
      sessionsSpawnArgs: sendArgs,
      dispatchMode: "send_to_speculative",
      speculativeSessionLabel: "octoclaw-speculative-gate",
      ttlMs: 60_000,
    });

    const blocked = evaluateNativeSpawnGate({
      sessionKeys: ["session-speculative-gate"],
      args: sendArgs,
    });

    expect(blocked.allowed).toBe(false);
    expect(blocked.reason).toBe("missing_pending_intent");
  });

  it("keeps ordinary spawn and speculative send intents from masking each other", () => {
    const key = "session-mixed-dispatch-mode";
    const now = Date.now();
    const spawnIntent = nativeSpawnIntentStore.create({
      workContractId: "wc-mixed-spawn",
      sessionKey: key,
      sessionsSpawnArgs: args,
      ttlMs: 60_000,
      now,
    });
    const sendArgs = {
      message: "Run delegated task through standby session.",
      label: "octoclaw-speculative-mixed",
      timeoutSeconds: 0,
    } as unknown as SessionsSpawnArgs;
    const sendIntent = nativeSpawnIntentStore.create({
      workContractId: "wc-mixed-send",
      sessionKey: key,
      sessionsSpawnArgs: sendArgs,
      dispatchMode: "send_to_speculative",
      speculativeSessionLabel: "octoclaw-speculative-mixed",
      ttlMs: 60_000,
      now: now + 1,
    });

    const spawnGate = evaluateNativeSpawnGate({ sessionKeys: [key], args });
    const sendGate = evaluateNativeSessionsSendGate({ sessionKeys: [key], args: sendArgs });

    expect(spawnGate.allowed).toBe(true);
    expect(spawnGate.allowed ? spawnGate.intent.spawnIntentId : "").toBe(spawnIntent.spawnIntentId);
    expect(sendGate.allowed).toBe(true);
    expect(sendGate.allowed ? sendGate.intent.spawnIntentId : "").toBe(sendIntent.spawnIntentId);
    expect(nativeSpawnIntentStore.get(spawnIntent.spawnIntentId)?.status).toBe("spawn_call_started");
    expect(nativeSpawnIntentStore.get(sendIntent.spawnIntentId)?.status).toBe("spawn_call_started");
  });

  it("checks every Slack session alias before blocking on a stale hash mismatch", () => {
    const staleSlackChannelKey = "agent:main:slack:channel:c0as4dappu3";
    const matchingSlackThreadKey = "agent:main:slack:channel:c0as4dappu3:thread:1777707495.459389";
    const staleIntent = nativeSpawnIntentStore.create({
      workContractId: "wc-stale-alias",
      sessionKey: staleSlackChannelKey,
      sessionsSpawnArgs: { ...args, task: "old stale planner args" },
      ttlMs: 60_000,
    });
    const matchingIntent = nativeSpawnIntentStore.create({
      workContractId: "wc-real-alias",
      sessionKey: matchingSlackThreadKey,
      sessionsSpawnArgs: args,
      ttlMs: 60_000,
    });

    const allowed = evaluateNativeSpawnGate({
      sessionKeys: [staleSlackChannelKey, matchingSlackThreadKey],
      args,
    });

    expect(allowed.allowed).toBe(true);
    expect(allowed.allowed ? allowed.intent.spawnIntentId : "").toBe(matchingIntent.spawnIntentId);
    expect(nativeSpawnIntentStore.get(staleIntent.spawnIntentId)?.status).toBe("planned");
    expect(nativeSpawnIntentStore.get(matchingIntent.spawnIntentId)?.status).toBe("spawn_call_started");
  });
});

describe("confirmNativeSpawn", () => {
  it("requires runId and refuses planned -> accepted", async () => {
    const contract = seedContract("session-confirm-planned");
    const intent = nativeSpawnIntentStore.create({
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      sessionsSpawnArgs: args,
      ttlMs: 60_000,
    });

    const missingRun = await confirmNativeSpawn({
      spawnIntentId: intent.spawnIntentId,
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      sessionsSpawnStatus: "accepted",
      notify: false,
    });
    expect(missingRun.ok).toBe(false);
    expect(missingRun.error).toBe("run_id_required");

    const bypass = await confirmNativeSpawn({
      spawnIntentId: intent.spawnIntentId,
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      sessionsSpawnStatus: "accepted",
      runId: "run-bypass",
      notify: false,
    });
    expect(bypass.ok).toBe(false);
    expect(bypass.error).toBe("invalid_status:planned");
    expect(loadWorkContract(contract.workContractId)?.delegate?.nativeBinding ?? null).toBeNull();
  });

  it("records native refs only after gate moved intent to spawn_call_started", async () => {
    const contract = seedContract();
    const intent = nativeSpawnIntentStore.create({
      workContractId: contract.workContractId,
      delegateTaskId: `delegate-task:${contract.workContractId}`,
      attemptId: `delegate-task:${contract.workContractId}:attempt:1`,
      sessionKey: contract.sessionKey,
      sessionsSpawnArgs: args,
      ttlMs: 60_000,
    });
    const gate = evaluateNativeSpawnGate({ sessionKeys: [contract.sessionKey], args });
    expect(gate.allowed).toBe(true);

    const result = await confirmNativeSpawn({
      spawnIntentId: intent.spawnIntentId,
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      sessionsSpawnStatus: "accepted",
      runId: "run-confirmed",
      childSessionKey: "child-session-confirmed",
      notify: false,
    });

    expect(result.ok).toBe(true);
    expect(result.status).toBe("accepted");
    expect(nativeSpawnIntentStore.get(intent.spawnIntentId)?.status).toBe("accepted");
    const updated = loadWorkContract(contract.workContractId);
    expect(updated?.status).toBe("sealed");
    expect(updated?.telemetry.dispatchExecuted).toBe(true);
    expect(updated?.telemetry.spawnExecuted).toBe(true);
    expect(updated?.delegate?.modelProfile).toBe("zhipu/GLM-5.1");
    expect(updated?.delegate?.nativeBinding?.runId).toBe("run-confirmed");
    expect(updated?.delegate?.nativeBinding?.childSessionKey).toBe("child-session-confirmed");
  });

  it("marks failed native spawn results without recording refs", async () => {
    const contract = seedContract("session-confirm-failed");
    const intent = nativeSpawnIntentStore.create({
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      sessionsSpawnArgs: args,
      ttlMs: 60_000,
    });
    const gate = evaluateNativeSpawnGate({ sessionKeys: [contract.sessionKey], args });
    expect(gate.allowed).toBe(true);

    const result = await confirmNativeSpawn({
      spawnIntentId: intent.spawnIntentId,
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      sessionsSpawnStatus: "error",
      error: "native rejected spawn",
      notify: false,
    });

    expect(result.ok).toBe(false);
    expect(result.status).toBe("failed");
    expect(nativeSpawnIntentStore.get(intent.spawnIntentId)?.status).toBe("failed");
    expect(loadWorkContract(contract.workContractId)?.delegate?.nativeBinding ?? null).toBeNull();
  });

  it("fails closed when WorkContract native refs cannot be written", async () => {
    const intent = nativeSpawnIntentStore.create({
      workContractId: "wc-missing-for-native-refs",
      sessionKey: "session-confirm-missing-contract",
      sessionsSpawnArgs: args,
      ttlMs: 60_000,
    });
    expect(evaluateNativeSpawnGate({ sessionKeys: ["session-confirm-missing-contract"], args }).allowed).toBe(true);

    const result = await confirmNativeSpawn({
      spawnIntentId: intent.spawnIntentId,
      workContractId: "wc-missing-for-native-refs",
      sessionKey: "session-confirm-missing-contract",
      sessionsSpawnStatus: "accepted",
      runId: "run-no-contract",
    });

    expect(result.ok).toBe(false);
    expect(result.error).toBe("work_contract_native_refs_write_failed");
    expect(nativeSpawnIntentStore.get(intent.spawnIntentId)?.status).toBe("spawn_call_started");
    expect(nativeSpawnIntentStore.get(intent.spawnIntentId)?.runId ?? null).toBeNull();
    expect(nativeSpawnIntentStore.get(intent.spawnIntentId)?.ackSentAt ?? null).toBeNull();
  });

  it("fails closed when the intent store is unavailable during accepted confirm", async () => {
    const contract = seedContract("session-confirm-store-unavailable");
    const intent = nativeSpawnIntentStore.create({
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      sessionsSpawnArgs: args,
      ttlMs: 60_000,
    });
    expect(evaluateNativeSpawnGate({ sessionKeys: [contract.sessionKey], args }).allowed).toBe(true);
    const storeError = new Error("database is locked");
    (storeError as Error & { code?: string }).code = "SQLITE_BUSY";
    vi.spyOn(nativeSpawnIntentStore, "get").mockImplementationOnce(() => {
      throw storeError;
    });

    const result = await confirmNativeSpawn({
      spawnIntentId: intent.spawnIntentId,
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      sessionsSpawnStatus: "accepted",
      runId: "run-store-busy",
      childSessionKey: "child-store-busy",
      notify: false,
    });

    expect(result.ok).toBe(false);
    expect(result.status).toBe("error");
    expect(result.error).toBe("sqlite_busy");
    expect(loadWorkContract(contract.workContractId)?.nativeSpawnRefs?.openclawRunId ?? null).toBeNull();
    expect(nativeSpawnIntentStore.get(intent.spawnIntentId)?.status).toBe("spawn_call_started");
  });

  it("rolls back WorkContract native refs when accepted intent transition fails after refs write", async () => {
    const contract = seedContract("session-confirm-transition-fails");
    const intent = nativeSpawnIntentStore.create({
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      sessionsSpawnArgs: args,
      ttlMs: 60_000,
    });
    expect(evaluateNativeSpawnGate({ sessionKeys: [contract.sessionKey], args }).allowed).toBe(true);
    const startedIntent = nativeSpawnIntentStore.get(intent.spawnIntentId);
    expect(startedIntent?.status).toBe("spawn_call_started");
    vi.spyOn(nativeSpawnIntentStore, "confirmAccepted").mockImplementationOnce(() => {
      updateWorkContract(contract.workContractId, (current) => ({
        ...current,
        mainContext: {
          ...current.mainContext,
          statusLine: "concurrent status update survives rollback",
        },
      }));
      return {
        ok: false,
        status: "error",
        intent: startedIntent ? { ...startedIntent, status: "expired" as const } : undefined,
        error: "intent_expired",
      };
    });

    const result = await confirmNativeSpawn({
      spawnIntentId: intent.spawnIntentId,
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      sessionsSpawnStatus: "accepted",
      runId: "run-transition-fails",
      childSessionKey: "child-transition-fails",
    });

    expect(result.ok).toBe(false);
    expect(result.error).toBe("intent_expired");
    const restored = loadWorkContract(contract.workContractId);
    expect(restored?.nativeSpawnRefs?.openclawRunId ?? null).toBeNull();
    expect(restored?.delegate?.nativeBinding ?? null).toBeNull();
    expect(restored?.telemetry.dispatchExecuted ?? false).toBe(false);
    expect(restored?.telemetry.spawnExecuted ?? false).toBe(false);
    expect(restored?.mainContext.statusLine).toBe("concurrent status update survives rollback");
    expect(nativeSpawnIntentStore.get(intent.spawnIntentId)?.status).toBe("spawn_call_started");
    expect(nativeSpawnIntentStore.get(intent.spawnIntentId)?.ackSentAt ?? null).toBeNull();
  });

  it("does not rollback over native refs written by a successful racing confirm", async () => {
    const contract = seedContract("session-confirm-race-rollback");
    const intent = nativeSpawnIntentStore.create({
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      sessionsSpawnArgs: args,
      ttlMs: 60_000,
    });
    expect(evaluateNativeSpawnGate({ sessionKeys: [contract.sessionKey], args }).allowed).toBe(true);
    const startedIntent = nativeSpawnIntentStore.get(intent.spawnIntentId);
    expect(startedIntent?.status).toBe("spawn_call_started");
    vi.spyOn(nativeSpawnIntentStore, "confirmAccepted").mockImplementationOnce(() => {
      updateWorkContract(contract.workContractId, (current) => {
        const nativeBinding = {
          ...(current.delegate?.nativeBinding ?? {}),
          flowId: "sessions_spawn:run-success-race",
          ownerKey: intent.delegateTaskId || contract.workContractId,
          controllerId: "octoclaw.delegate",
          revision: 1,
          expectedRevision: 1,
          runId: "run-success-race",
          childRunId: "run-success-race",
          childSessionKey: "child-success-race",
          syncMode: "managed" as const,
          status: "running" as const,
          lastMutation: "runTask" as const,
          lastMutationApplied: true,
        };
        return {
          ...current,
          delegate: current.delegate ? { ...current.delegate, nativeBinding } : current.delegate,
          nativeSpawnRefs: {
            ...current.nativeSpawnRefs,
            openclawRunId: "run-success-race",
            childSessionKey: "child-success-race",
            requesterSessionKey: current.sessionKey,
            spawnIntentId: intent.spawnIntentId,
            spawnBackend: "sessions_spawn_planner",
            spawnMode: "run",
          },
          continuity: {
            ...current.continuity,
            preferredChildSessionKey: "child-success-race",
            preferredRunId: "run-success-race",
          },
          telemetry: {
            ...current.telemetry,
            dispatchExecuted: true,
            spawnExecuted: true,
            childSessionKey: "child-success-race",
            childRunId: "run-success-race",
          },
          mainContext: {
            ...current.mainContext,
            visibleIds: {
              ...current.mainContext.visibleIds,
              childSessionKey: "child-success-race",
              openclawRunId: "run-success-race",
              spawnIntentId: intent.spawnIntentId,
            },
          },
        };
      });
      return {
        ok: false,
        status: "conflict",
        intent: startedIntent ? { ...startedIntent, status: "accepted" as const, runId: "run-success-race" } : undefined,
        error: "run_id_conflict",
        existingRunId: "run-success-race",
      };
    });

    const result = await confirmNativeSpawn({
      spawnIntentId: intent.spawnIntentId,
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      sessionsSpawnStatus: "accepted",
      runId: "run-loser-race",
      childSessionKey: "child-loser-race",
      notify: false,
    });

    expect(result.ok).toBe(false);
    expect(result.status).toBe("conflict");
    expect(result.error).toBe("run_id_conflict");
    const updated = loadWorkContract(contract.workContractId);
    expect(updated?.nativeSpawnRefs?.openclawRunId).toBe("run-success-race");
    expect(updated?.nativeSpawnRefs?.childSessionKey).toBe("child-success-race");
    expect(updated?.delegate?.nativeBinding?.runId).toBe("run-success-race");
    expect(updated?.telemetry.spawnExecuted).toBe(true);
  });

  it("treats same-run confirm as idempotent and different-run confirm as conflict", async () => {
    const contract = seedContract("session-confirm-idempotent");
    const intent = nativeSpawnIntentStore.create({
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      sessionsSpawnArgs: args,
      ttlMs: 60_000,
    });
    expect(evaluateNativeSpawnGate({ sessionKeys: [contract.sessionKey], args }).allowed).toBe(true);

    const first = await confirmNativeSpawn({
      spawnIntentId: intent.spawnIntentId,
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      sessionsSpawnStatus: "accepted",
      runId: "run-once",
      childSessionKey: "child-once",
      notify: false,
    });
    const second = await confirmNativeSpawn({
      spawnIntentId: intent.spawnIntentId,
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      sessionsSpawnStatus: "accepted",
      runId: "run-once",
      childSessionKey: "child-spoofed",
      notify: false,
    });
    const conflict = await confirmNativeSpawn({
      spawnIntentId: intent.spawnIntentId,
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      sessionsSpawnStatus: "accepted",
      runId: "run-different",
      notify: false,
    });

    expect(first.status).toBe("accepted");
    expect(second.ok).toBe(true);
    expect(second.status).toBe("idempotent");
    expect(conflict.ok).toBe(false);
    expect(conflict.status).toBe("conflict");
    expect(loadWorkContract(contract.workContractId)?.delegate?.nativeBinding?.runId).toBe("run-once");
    expect(loadWorkContract(contract.workContractId)?.delegate?.nativeBinding?.childSessionKey).toBe("child-once");
  });

  it("retries ACK on idempotent same-run confirm when the first accepted confirm skipped notification", async () => {
    vi.spyOn(await import("../replay/replay.js"), "recordPolicyReplay").mockResolvedValue(undefined);

    const contract = seedContract("slack:channel:C1");
    const intent = nativeSpawnIntentStore.create({
      workContractId: contract.workContractId,
      delegateTaskId: `delegate-task:${contract.workContractId}`,
      attemptId: `delegate-task:${contract.workContractId}:attempt:1`,
      sessionKey: contract.sessionKey,
      sessionsSpawnArgs: args,
      ttlMs: 60_000,
    });
    expect(evaluateNativeSpawnGate({ sessionKeys: [contract.sessionKey], args }).allowed).toBe(true);

    const first = await confirmNativeSpawn({
      spawnIntentId: intent.spawnIntentId,
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      sessionsSpawnStatus: "accepted",
      runId: "run-retry-ack",
      childSessionKey: "child-retry-ack",
      notify: false,
    });
    expect(first.ok).toBe(true);
    expect(first.status).toBe("accepted");
    expect(first.ackSent).toBe(false);
    expect(nativeSpawnIntentStore.get(intent.spawnIntentId)?.ackSentAt ?? null).toBeNull();
    expect(mockSendIMMessage).not.toHaveBeenCalled();

    const retry = await confirmNativeSpawn({
      spawnIntentId: intent.spawnIntentId,
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      stateKey: contract.sessionKey,
      sessionsSpawnStatus: "accepted",
      runId: "run-retry-ack",
      childSessionKey: "child-retry-ack",
      replyToMessageId: "1700000000.000100",
    });

    expect(retry.ok).toBe(true);
    expect(retry.status).toBe("idempotent");
    expect(retry.ackSent).toBe(true);
    expect(mockSendIMMessage).toHaveBeenCalledOnce();
    expect(nativeSpawnIntentStore.get(intent.spawnIntentId)?.ackSentAt ?? null).not.toBeNull();
  });

  it("does not mark ACK on failed notification and allows an idempotent retry to send it", async () => {
    mockSendIMMessage
      .mockResolvedValueOnce({ sent: false, error: "timeout" })
      .mockResolvedValueOnce({ sent: true, threadTs: "1700000000.000100" });
    vi.spyOn(await import("../replay/replay.js"), "recordPolicyReplay").mockResolvedValue(undefined);

    const contract = seedContract("slack:channel:C2");
    const intent = nativeSpawnIntentStore.create({
      workContractId: contract.workContractId,
      delegateTaskId: `delegate-task:${contract.workContractId}`,
      attemptId: `delegate-task:${contract.workContractId}:attempt:1`,
      sessionKey: contract.sessionKey,
      sessionsSpawnArgs: args,
      ttlMs: 60_000,
    });
    expect(evaluateNativeSpawnGate({ sessionKeys: [contract.sessionKey], args }).allowed).toBe(true);

    const first = await confirmNativeSpawn({
      spawnIntentId: intent.spawnIntentId,
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      stateKey: contract.sessionKey,
      sessionsSpawnStatus: "accepted",
      runId: "run-ack-fails-once",
      childSessionKey: "child-ack-fails-once",
      replyToMessageId: "1700000000.000200",
    });

    expect(first.ok).toBe(true);
    expect(first.status).toBe("accepted");
    expect(first.ackSent).toBe(false);
    expect(first.ackSkipped).toBe(false);
    expect(nativeSpawnIntentStore.get(intent.spawnIntentId)?.ackSentAt ?? null).toBeNull();

    const retry = await confirmNativeSpawn({
      spawnIntentId: intent.spawnIntentId,
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      stateKey: contract.sessionKey,
      sessionsSpawnStatus: "accepted",
      runId: "run-ack-fails-once",
      childSessionKey: "child-ack-fails-once",
      replyToMessageId: "1700000000.000200",
    });

    expect(retry.ok).toBe(true);
    expect(retry.status).toBe("idempotent");
    expect(retry.ackSent).toBe(true);
    expect(mockSendIMMessage).toHaveBeenCalledTimes(2);
    expect(nativeSpawnIntentStore.get(intent.spawnIntentId)?.ackSentAt ?? null).not.toBeNull();
  });

  it("does not mark ACK until accepted confirm notification is sent or acceptably skipped", async () => {
    const contract = seedContract("session-confirm-ack-order");
    const intent = nativeSpawnIntentStore.create({
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      sessionsSpawnArgs: args,
      ttlMs: 60_000,
    });

    const plannedConfirm = await confirmNativeSpawn({
      spawnIntentId: intent.spawnIntentId,
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      sessionsSpawnStatus: "accepted",
      runId: "run-too-early",
    });
    expect(plannedConfirm.ok).toBe(false);
    expect(nativeSpawnIntentStore.get(intent.spawnIntentId)?.ackSentAt ?? null).toBeNull();

    expect(evaluateNativeSpawnGate({ sessionKeys: [contract.sessionKey], args }).allowed).toBe(true);
    const accepted = await confirmNativeSpawn({
      spawnIntentId: intent.spawnIntentId,
      workContractId: contract.workContractId,
      sessionKey: contract.sessionKey,
      sessionsSpawnStatus: "accepted",
      runId: "run-ack-after-accepted",
    });

    expect(accepted.ok).toBe(true);
    expect(accepted.ackSent).toBe(false);
    expect(nativeSpawnIntentStore.get(intent.spawnIntentId)?.ackSentAt ?? null).toBeNull();
  });

});
